spring:
  datasource:
    url:    jdbc:postgresql://localhost:5432/railways
    username: railways
    password: r@ilw@ys
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8080

